var h=null;(function(b,e){var c=new b.b.d;c.c=function(){var c=e("link[rel='toc']").D("href");b.v.c(c)};b.C=b.C||c})(window.a=window.a||{},jQuery);
(function(b,e){var c=new b.b.d;c.i(b.b.k);c.i({c:function(b){b=b||{};this.url=b.url;this.title=b.title;this.N=b.N;this.t=b.t;this.content=b.content},G:function(f){var d=this;e.B({type:"GET",url:this.url,M:function(e){d.content=c.F(e);d.w(b.f.l);"function"==typeof f&&f(d.content)}})}});c.extend({F:function(b){return b.split(/<\/?body[^>]*>/)[1]}});b.q=b.q||c})(window.a=window.a||{},jQuery);
(function(b){var e=new b.b.d,c=b.j.s;e.extend({p:{o:h,h:h,next:h},display:function(f){c.find("url",f);c.h().n(b.f.l,function(){e.p.o=new b.g(c.o());e.p.next=new b.g(c.next())});this.p.h=new b.g(c.h())}});b.u=b.u||e})(window.a=window.a||{},jQuery);(function(b){var e=new b.b.d;e.extend(b.b.k);e.extend({c:function(c){b.j.n(b.f.r,this.L);b.j.H(c)},L:function(){this.navigate(window.location.pathname)},U:function(){},navigate:function(c){b.u.display(c)}});b.v=b.v||e})(window.a=window.a||{},jQuery);
(window.a=window.a||{}).f={r:"TOC loaded!",l:"Content loaded!"};
(function(b,e){function c(b,c){e.B({type:"GET",url:b,M:function(b){"function"==typeof c&&c(b)},error:function(){}})}function f(c){c=e(c).find("[itemscope]");return e.map(c,function(c){c=e(c);return new b.q({title:c.find("[itemprop='title']").text(),url:c.find("[itemprop='url']").D("href"),t:c.find("[itemprop='byline']").text()})})}var d=new b.b.d;d.extend(b.b.k);d.s=new b.b.A;d.H=function(e){c(e,function(c){c=f(c);d.s.c(c);d.w(b.f.r)})};b.j=b.j||d})(window.a=window.a||{},jQuery);
(function(b){b.b=b.b||{};b.b.A=function(){var b=0,c=[];return{c:function(b){this.clear();c=b},add:function(b){c.push(b)},find:function(f,d){for(var g=c.length;0<g;)if(g--,c[g][f]==d)return b=g,c[g];return h},h:function(){return!this.I()?h:c[b]},next:function(){return!this.J()?h:c[b+1]},o:function(){return!this.K()?h:c[b-1]},T:function(){b=0},clear:function(){b=0;c=[]},I:function(){return 0<c.length},J:function(){return b+1<c.length},K:function(){return 0<b}}}})(window.a=window.a||{},jQuery);
(function(b){b.b=b.b||{};b.b.d=function(){function b(){this.c.apply(this,arguments)}b.prototype.c=function(){};b.extend=function(c){var f=c.P,d;for(d in c)b[d]=c[d];f&&f(b)};b.i=function(c){var f=c.S,d;for(d in c)b.prototype[d]=c[d];f&&f(b)};b.z=function(b){var f=this;return function(){return b.apply(f,arguments)}};b.prototype.z=b.z;return b}})(window.a=window.a||{},jQuery);
(function(b,e){function c(b,c){b.e||(b.e={});b.e[c]||(b.e[c]=[]);return b.e[c]}b.b=b.b||{};b.b.k={n:function(b,d){this.e||(this.e=[]);if("function"!=typeof d)throw new TypeError("not a function");if("string"!=typeof b)throw new TypeError("not a valid event identifier");c(this,b).push(d)},Q:function(b,d){var g=c(this,b);return 0<=e.R(d,g)},w:function(b){if("string"!=typeof b)throw new TypeError("not a valid event identifier");var d=c(this,b),g=Array.prototype.slice.call(arguments,1);e.O(d,function(){try{this.apply(this,
g)}catch(b){}})}}})(window.a=window.a||{},jQuery);(function(b,e){var c=new b.b.d;c.i(b.b.k);c.i({c:function(c){this.m=c;this.m.n(b.f.l,this.create);this.m.G()},create:function(){e("body").append(this.m.content)}});c.extend({});b.g=b.g||c})(window.a=window.a||{},jQuery);
