!function(a,c){var b=new a.util.Module;b.init=function(){var b=c("link[rel='toc']").attr("href");a.controller.init(b)};a.app=a.app||b}(window.pulp=window.pulp||{},jQuery);"use strict";
!function(a,c){var b=new a.util.Module;b.include(a.util.observable);b.include({init:function(b){b=b||{};this.url=b.url;this.title=b.title;this.thumbnail=b.thumbnail;this.byline=b.byline;this.content=b.content},fetch:function(d){var e=this;c.ajax({type:"GET",url:this.url,success:function(c){e.content=b.extractContent(c);e.notify(a.events.CONTENT_LOADED);"function"==typeof d&&d(e.content)}})}});b.extend({extractContent:function(b){return b.split(/<\/?body[^>]*>/)[1]}});a.Article=a.Article||b}(window.pulp=
window.pulp||{},jQuery);"use strict";!function(a){var c=new a.util.Module,b=a.model.articles;c.extend({views:{previous:null,current:null,next:null},display:function(d){b.find("url",d);b.current().observe(a.events.CONTENT_LOADED,function(){c.views.previous=new a.View(b.previous());c.views.next=new a.View(b.next())});this.views.current=new a.View(b.current())}});a.carousel=a.carousel||c}(window.pulp=window.pulp||{},jQuery);"use strict";
!function(a){var c=new a.util.Module;c.extend(a.util.observable);c.extend({init:function(b){a.model.observe(a.events.TOC_LOADED,this.setup);a.model.getToc(b)},setup:function(){this.navigate(window.location.pathname)},route:function(){},navigate:function(b){a.carousel.display(b);this.route(b)}});a.controller=a.controller||c}(window.pulp=window.pulp||{},jQuery);"use strict";!function(a){a.events={TOC_LOADED:"TOC loaded!",CONTENT_LOADED:"Content loaded!"}}(window.pulp=window.pulp||{},jQuery);"use strict";
!function(a,c){function b(b,a,d){c.ajax({type:"GET",url:b,success:function(b){"function"==typeof a&&a(b)},error:function(b,a){"function"==typeof d&&d(a)}})}function d(b){b=c(b).find("[itemscope]");return c.map(b,function(b){b=c(b);return new a.Article({title:b.find("[itemprop='title']").text(),url:b.find("[itemprop='url']").attr("href"),byline:b.find("[itemprop='byline']").text()})})}var e=new a.util.Module;e.extend(a.util.observable);e.articles=new a.util.Collection;e.getToc=function(c){b(c,function(b){b=
d(b);e.articles.init(b);e.notify(a.events.TOC_LOADED)})};a.model=a.model||e}(window.pulp=window.pulp||{},jQuery);
!function(a){a.util=a.util||{};a.util.Collection=function(){var a=0,b=[];return{init:function(a){this.clear();b=a},add:function(a){b.push(a)},find:function(d,e){for(var f=b.length;0<f;)if(f--,b[f][d]==e)return a=f,b[f];return null},current:function(){return!this.hasItems()?null:b[a]},next:function(){return!this.hasNext()?null:b[a+1]},previous:function(){return!this.hasPrevious()?null:b[a-1]},rewind:function(){a=0},clear:function(){a=0;b=[]},hasItems:function(){return 0<b.length},hasNext:function(){return a+
1<b.length},hasPrevious:function(){return 0<a}}}}(window.pulp=window.pulp||{},jQuery);"use strict";
!function(a){a.util=a.util||{};a.util.Module=function(a){var b=function(){this.init.apply(this,arguments)};b.prototype.init=function(){};if(a){for(var d in a)b[d]=SuperClass.clone(a[d]);for(d in a.prototype)b.prototype[d]=SuperClass.clone(a.prototype[d]);b._super=a;b.prototype._super=a.prototype}b.extend=function(a){var d=a.extended,c;for(c in a)b[c]=a[c];d&&d(b)};b.include=function(a){var d=a.included,c;for(c in a)b.prototype[c]=a[c];d&&d(b)};b.proxy=function(a){var b=this;return function(){return a.apply(b,
arguments)}};b.prototype.proxy=b.proxy;return b.prototype._class=b}}(window.pulp=window.pulp||{},jQuery);"use strict";
!function(a,c){function b(a,b){a.observers||(a.observers={});a.observers[b]||(a.observers[b]=[]);return a.observers[b]}a.util=a.util||{};a.util.observable={observe:function(a,c){this.observers||(this.observers=[]);if("function"!=typeof c)throw new TypeError("not a function");if("string"!=typeof a)throw new TypeError("not a valid event identifier");b(this,a).push(c)},hasObserver:function(a,e){var f=b(this,a);return 0<=c.inArray(e,f)},notify:function(a){if("string"!=typeof a)throw new TypeError("not a valid event identifier");
var e=b(this,a),f=Array.prototype.slice.call(arguments,1);c.each(e,function(){try{this.apply(this,f)}catch(a){}})}}}(window.pulp=window.pulp||{},jQuery);"use strict";!function(a,c){var b=new a.util.Module;b.include(a.util.observable);b.include({init:function(b){this.article=b;this.article.observe(a.events.CONTENT_LOADED,this.create);this.article.fetch()},create:function(){c("body").append(this.article.content)}});b.extend({});a.View=a.View||b}(window.pulp=window.pulp||{},jQuery);
